apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod

resources:
- ../../base
- config-map.yaml

patches:
 - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: hugin-ingress
   path: ingress-patch.yaml

images:
- name: dummy.io/hugin/hugin
  newTag: 1.0.0