apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev

resources:
- ../../base
- config-map.yaml

images:
- name: dummy.io/hugin/hugin
  newName: dummy.io/hugin/dev-hugin
  newTag: 0.0.1-SNAPSHOT-6d7a011