apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/part-of: hugin
  name: prod
spec: {}
---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/part-of: hugin
  name: hugin-sa
  namespace: prod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/part-of: hugin
  name: hugin-role
  namespace: prod
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/part-of: hugin
  name: hugin-role-binding
  namespace: prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hugin-role
subjects:
- kind: ServiceAccount
  name: hugin-sa
  namespace: prod
---
apiVersion: v1
data:
  kubernetes.namespace: prod
  my-var: Hello from prod env config
  spring.cloud.kubernetes.client.namespace: prod
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: hugin-cm
  name: hugin-cm
  namespace: prod
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app.kubernetes.io/name: hugin-svc
    app.kubernetes.io/part-of: hugin
  name: hugin-svc
  namespace: prod
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: hugin-app
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: hugin-app
    app.kubernetes.io/part-of: hugin
  name: hugin-app
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: hugin-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hugin-app
    spec:
      containers:
      - env:
        - name: SPRING_CLOUD_KUBERNETES_CLIENT_NAMESPACE
          valueFrom:
            configMapKeyRef:
              key: spring.cloud.kubernetes.client.namespace
              name: hugin-cm
        - name: MY_VAR
          valueFrom:
            configMapKeyRef:
              key: my-var
              name: hugin-cm
        image: dummy.io/hugin/hugin:1.0.0
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: hugin
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 6
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 2Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /tmp
          name: hugin-tmp-dir
      serviceAccountName: hugin-sa
      volumes:
      - emptyDir:
          medium: Memory
          sizeLimit: 500Mi
        name: hugin-tmp-dir
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app.kubernetes.io/name: hugin-ingress
    app.kubernetes.io/part-of: hugin
  name: hugin-ingress
  namespace: prod
spec:
  ingressClassName: nginx
  rules:
  - host: hugin.test
    http:
      paths:
      - backend:
          service:
            name: hugin-svc
            port:
              name: http
        path: /
        pathType: ImplementationSpecific
