apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev

resources:
- ../../base
- config-map.yaml

patches:
 - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: hugin-ingress
   path: ingress-patch.yaml

 - target:
      group: apps
      version: v1
      kind: Deployment
      name: hugin-app
   path: deployment-patch.yaml

images:
- name: dummy.io/hugin/hugin
  newName: dummy.io/hugin/dev-hugin
  newTag: 0.0.2-SNAPSHOT-0936056