apiVersion: v1
kind: Service
metadata:
  labels:
    app: hugin
  name: hugin
  namespace: hugin
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hugin
  type: ClusterIP
status:
  loadBalancer: {}
