apiVersion: v1
kind: ServiceAccount
metadata:
  name: hugin-sa
  namespace: hugin
  labels:
    app.kubernetes.io/part-of: hugin
  annotations:
    argocd.argoproj.io/sync-wave: "0"
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hugin-role
  namespace: hugin
  labels:
    app.kubernetes.io/part-of: hugin
  annotations:
    argocd.argoproj.io/sync-wave: "0"
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hugin-role-binding
  namespace: hugin
  labels:
    app.kubernetes.io/part-of: hugin
  annotations:
    argocd.argoproj.io/sync-wave: "0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hugin-role
subjects:
  - kind: ServiceAccount
    name: hugin-sa
    namespace: hugin