name: Render Manifests
on:
  push:
    paths-ignore:
    - '**/README.adoc'
    - minikube
    branches:
    - main

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [dev, prod]
    permissions:
      contents: 
        write
    steps:
    - uses: actions/checkout@v4
      with:
        # fetch-depth: 0 needed to get all branches
        fetch-depth: 0
    - uses: fregante/setup-git-user@v2
    - 
      name: Render manifests
      run: |
        kustomize build env/${{ matrix.env }} --output /tmp/manifest.yaml
        if ! git checkout deploy/${{ matrix.env }} -- ; then
          git checkout --orphan deploy/${{ matrix.env }}
          git rm -rf .
          cp /tmp/manifest.yaml .
          git add manifest.yaml
          git commit -m "${{ github.event.head_commit.message }}"
          git push --set-upstream origin deploy/${{ matrix.env }}
        else
          cp /tmp/manifest.yaml .
        fi 
    -
      name: Deploy to ${{ matrix.env }}
      if: ${{ matrix.env != 'prod' }}
      run: |
        if ! git diff --quiet HEAD ; then 
          git add manifest.yaml
          git commit -m "${{ github.event.head_commit.message }}"
          git push --set-upstream origin deploy/${{ matrix.env }}
        fi
    -
      name: Deploy PR to ${{ matrix.env }}
      uses: peter-evans/create-pull-request@v7
      if: ${{ matrix.env == 'prod' }}
      with:
        title: ${{ github.event.head_commit.message }}
        commit-message: ${{ github.event.head_commit.message }}
        base: deploy/${{ matrix.env }}
        branch: pr/deploy/env/${{ matrix.env }}