on:
  pull_request:
    types:
        [labeled]
    branches:
     - main

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy_preview:
    runs-on: ubuntu-latest
    if: contains( github.event.pull_request.labels.*.name, 'preview')
    steps:
      - run: echo 'Preview requested for branch ${{ env.BRANCH_NAME }}'